--CREATE ROLE application_user WITH
--  LOGIN
--  NOSUPERUSER
--  INHERIT
--  NOCREATEDB
--  NOCREATEROLE
--  NOREPLICATION
--  ENCRYPTED PASSWORD 'SCRAM-SHA-256$4096:0kSejqP57s0JydAZaWUy/A==$E2+YiCtQdNleUxIv60kuWYuqkCubqo/O8pCruqsomZM=:VuZad5nXSnug2pSzmxctpB80lIMDxN+dvBqtQdY/sn4=';
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'application_user') THEN
    CREATE ROLE application_user WITH
      LOGIN
      NOSUPERUSER
      INHERIT
      NOCREATEDB
      NOCREATEROLE
      NOREPLICATION
      ENCRYPTED PASSWORD 'SCRAM-SHA-256$4096:0kSejqP57s0JydAZaWUy/A==$E2+YiCtQdNleUxIv60kuWYuqkCubqo/O8pCruqsomZM=:VuZad5nXSnug2pSzmxctpB80lIMDxN+dvBqtQdY/sn4=';
  END IF;
END $$;


GRANT INSERT, SELECT, UPDATE, DELETE, REFERENCES ON ALL TABLES IN SCHEMA public TO "${username}";
GRANT USAGE ON ALL SEQUENCES IN SCHEMA public TO "${username}";
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA public TO "${username}";
